{% set name = "rocketry" %}
{% set version = "2.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/rocketry-{{ version }}.tar.gz
  sha256: 832722ec6d063e03f68920f162f322ffdce0e27a963c447f18ff7802496bc45b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - pydantic
    - python >=3.7
    - python-dateutil
    - redbird >=0.5.0

test:
  imports:
    - rocketry
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Miksus/rocketry
  doc_url: https://rocketry.readthedocs.io/en/stable/
  summary: Advanced scheduling framework
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
